server:
  port: 8088

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  documentation:
    swagger:
      v2:
        host: api-docs
        use-model-v3: true

stackoverflowurl:
  https://api.stackexchange.com/2.3/search

